// Mock disaster reports data
export const mockReports = [
    {
      id: "DZ-20240621-ABC123",
      type: "flood",
      description:
        "Heavy flooding on the main road near Kaneshie Market. Water level is about 2 feet high and rising. Several cars are stuck and people are stranded.",
      location: "Kaneshie Market, Accra",
      coordinates: "5.5563, -0.2297",
      severity: "high",
      casualties: "0",
      reporterName: "Kwame Asante",
      reporterPhone: "+233244123456",
      reporterType: "citizen",
      images: ["/placeholder.svg?height=200&width=300&text=Flood+Scene"],
      status: "in_progress",
      createdAt: "2024-06-21T08:30:00Z",
      updatedAt: "2024-06-21T09:15:00Z",
      assignedTo: "Greater Accra NADMO",
      responseTime: null,
      notes: "Emergency response team dispatched. Evacuation in progress.",
    },
    {
      id: "DZ-20240621-DEF456",
      type: "fire",
      description:
        "Large fire at Kumasi Central Market. Multiple shops affected. Fire service on scene but need additional support.",
      location: "Kumasi Central Market",
      coordinates: "6.6885, -1.6244",
      severity: "critical",
      casualties: "3 injured",
      reporterName: "Mary Osei",
      reporterPhone: "+233201987654",
      reporterType: "citizen",
      images: [
        "/placeholder.svg?height=200&width=300&text=Market+Fire",
        "/placeholder.svg?height=200&width=300&text=Fire+Damage",
      ],
      status: "resolved",
      createdAt: "2024-06-20T14:20:00Z",
      updatedAt: "2024-06-20T18:45:00Z",
      assignedTo: "Ashanti NADMO",
      responseTime: 12,
      notes: "Fire contained. 3 people treated for smoke inhalation. Market section closed for investigation.",
    },
    {
      id: "DZ-20240621-GHI789",
      type: "accident",
      description: "Multi-vehicle accident on Tema-Accra highway near Spintex junction. Traffic heavily backed up.",
      location: "Tema-Accra Highway, Spintex",
      coordinates: "5.6698, 0.0166",
      severity: "medium",
      casualties: "2 injured",
      reporterName: "Anonymous",
      reporterPhone: "",
      reporterType: "anonymous",
      images: ["/placeholder.svg?height=200&width=300&text=Highway+Accident"],
      status: "resolved",
      createdAt: "2024-06-21T07:45:00Z",
      updatedAt: "2024-06-21T08:30:00Z",
      assignedTo: "Greater Accra NADMO",
      responseTime: 25,
      notes: "Vehicles cleared. 2 people taken to hospital with minor injuries.",
    },
    {
      id: "DZ-20240620-JKL012",
      type: "landslide",
      description: "Landslide blocking road to Cape Coast. Heavy rains caused soil erosion on hillside.",
      location: "Cape Coast-Elmina Road",
      coordinates: "5.1053, -1.2466",
      severity: "high",
      casualties: "0",
      reporterName: "Grace Mensah",
      reporterPhone: "+233244567890",
      reporterType: "citizen",
      images: ["/placeholder.svg?height=200&width=300&text=Landslide+Road"],
      status: "in_progress",
      createdAt: "2024-06-20T16:30:00Z",
      updatedAt: "2024-06-20T17:00:00Z",
      assignedTo: "Central NADMO",
      responseTime: null,
      notes: "Road clearance equipment dispatched. Alternative route advised.",
    },
    {
      id: "DZ-20240619-MNO345",
      type: "storm",
      description: "Severe thunderstorm with strong winds. Several trees down and power lines affected.",
      location: "Tamale Township",
      coordinates: "9.4034, -0.8424",
      severity: "medium",
      casualties: "0",
      reporterName: "Ibrahim Mohammed",
      reporterPhone: "+233209876543",
      reporterType: "citizen",
      images: ["/placeholder.svg?height=200&width=300&text=Storm+Damage"],
      status: "resolved",
      createdAt: "2024-06-19T20:15:00Z",
      updatedAt: "2024-06-19T22:30:00Z",
      assignedTo: "Northern NADMO",
      responseTime: 45,
      notes: "Trees cleared. Power restored. No casualties reported.",
    },
    {
      id: "DZ-20240621-PQR678",
      type: "fire",
      description: "Bush fire spreading near residential area in Sunyani. Wind is pushing fire towards homes.",
      location: "Sunyani Residential Area",
      coordinates: "7.3392, -2.3265",
      severity: "critical",
      casualties: "0",
      reporterName: "Akosua Boateng",
      reporterPhone: "+233244111222",
      reporterType: "citizen",
      images: ["/placeholder.svg?height=200&width=300&text=Bush+Fire"],
      status: "new",
      createdAt: "2024-06-21T11:20:00Z",
      updatedAt: "2024-06-21T11:20:00Z",
      assignedTo: null,
      responseTime: null,
      notes: "",
    },
    {
      id: "DZ-20240618-STU901",
      type: "other",
      description: "False alarm - reported gas leak was actually a sewage issue. No emergency response needed.",
      location: "East Legon, Accra",
      coordinates: "5.6500, -0.1500",
      severity: "low",
      casualties: "0",
      reporterName: "John Doe",
      reporterPhone: "+233244999888",
      reporterType: "citizen",
      images: [],
      status: "fake",
      createdAt: "2024-06-18T10:00:00Z",
      updatedAt: "2024-06-18T11:30:00Z",
      assignedTo: "Greater Accra NADMO",
      responseTime: 90,
      notes: "Investigation revealed no emergency. Marked as false report.",
    },
  ]
  
  export const disasterTypes = [
    { value: "flood", label: "Flood", icon: "🌊", color: "blue" },
    { value: "fire", label: "Fire", icon: "🔥", color: "red" },
    { value: "accident", label: "Accident", icon: "🚗", color: "orange" },
    { value: "landslide", label: "Landslide", icon: "⛰️", color: "brown" },
    { value: "storm", label: "Storm", icon: "⛈️", color: "purple" },
    { value: "earthquake", label: "Earthquake", icon: "🌍", color: "yellow" },
    { value: "other", label: "Other", icon: "⚠️", color: "gray" },
  ]
  
  export const statusConfig = {
    pending: {
      label: "Pending",
      color: "blue",
      bgColor: "bg-blue-50",
      textColor: "text-blue-700",
      borderColor: "border-blue-200",
    },
    new: { label: "New", color: "red", bgColor: "bg-red-50", textColor: "text-red-700", borderColor: "border-red-200" },
    in_progress: {
      label: "In Progress",
      color: "yellow",
      bgColor: "bg-yellow-50",
      textColor: "text-yellow-700",
      borderColor: "border-yellow-200",
    },
    resolved: {
      label: "Resolved",
      color: "green",
      bgColor: "bg-green-50",
      textColor: "text-green-700",
      borderColor: "border-green-200",
    },
    fake: {
      label: "Fake",
      color: "gray",
      bgColor: "bg-gray-50",
      textColor: "text-gray-700",
      borderColor: "border-gray-200",
    },
  }
  
  export const severityConfig = {
    low: { label: "Low", color: "green", bgColor: "bg-green-50", textColor: "text-green-700" },
    medium: { label: "Medium", color: "yellow", bgColor: "bg-yellow-50", textColor: "text-yellow-700" },
    high: { label: "High", color: "orange", bgColor: "bg-orange-50", textColor: "text-orange-700" },
    critical: { label: "Critical", color: "red", bgColor: "bg-red-50", textColor: "text-red-700" },
  }
  